trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
      
  - script: cd Terraform
    displayName: 'Change directory to Terraform'
      
  - task: TerraformCLI@0
    displayName: 'Initializing Terraform'
    env:
      GOOGLE_CREDENTIALS: $(google_credentials)
      BILLING_AC_ID: $(billing_ac_id)
    inputs:
      command: 'init -reconfigure'
      workingDirectory: 'Terraform'
      
  - task: PowerShell@2
    displayName: 'Terraform Plan'
    env:
      GOOGLE_CREDENTIALS: $(google_credentials)
      BILLING_AC_ID: $(billing_ac_id)
    inputs:
      targetType: 'inline'
      script: |
         terraform plan -var project_id=$env:project_id -var billing_ac_id=$env:billing_ac_id
      workingDirectory: 'Terraform'
