trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Terraform
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.9.2'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd Terraform
        terraform init -reconfigure -input=false \
          -backend-config="bucket=main_project_state_143" \
          -backend-config="prefix=terraform/state" \
          -backend-config="credentials=$(GOOGLE_CREDENTIALS_JSON)"
