trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Terraform
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.9.2'

  - script: |
      echo "Initializing Terraform..."
      terraform init -reconfigure -backend-config="bucket=main_project_state_143" \
                     -backend-config="prefix=terraform/state" \
                     -backend-config="credentials=$(GOOGLE_CREDENTIALS_JSON)"
      terraform apply -auto-approve
    env:
      GOOGLE_CREDENTIALS_JSON: $(Build.SourcesDirectory)/gcp_credentials.json
    displayName: 'Run Terraform'
