- hosts: master
  become: yes
  tasks:
    - name: Start the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all >> cluster.txt
      args:
        chdir: $HOME
        creates: cluster.txt
 
    - name: Create .kube directory
      become: yes
      become_user: vengalasanjay000
      file:
        path: $HOME/.kube
        state: directory
        mode: '0755'
 
    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vengalasanjay000/.kube/config
        remote_src: yes
        owner: ubuntu
 
    - name: Install Pod network
      become: yes
      become_user: vengalasanjay000
      shell: kubectl apply -f "https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml" >> pod_setup.txt
      args:
        chdir: $HOME
        creates: pod_setup.txt
