name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Change directory to Terraform
        run: cd Terraform

      - name: Initialize Terraform 
        run: terraform init 
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          BILLING_AC_ID: ${{ secrets.BILLING_AC_ID }}
        working-directory: Terraform

      - name: Terraform Plan and Apply
        run: |
          terraform plan -var project_id=${{ secrets.PROJECT_ID }}
          terraform apply --auto-approve -var project_id=${{ secrets.PROJECT_ID }} 
          terraform destroy --auto-approve -var project_id=${{ secrets.PROJECT_ID }} 
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          BILLING_AC_ID: ${{ secrets.BILLING_AC_ID }}
        working-directory: Terraform
