name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write public key to file
        run: echo "${{ secrets.PUBLIC_KEY }}" > Terraform/public_key.pub

      - name: Write private key to file
        run: echo "${{ secrets.PRIVATE_KEY }}" > Terraform/private_key.pem

      - name: Set private key file permissions
        run: chmod 600 Terraform/private_key.pem

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        working-directory: Terraform

      - name: Terraform Plan
        run: terraform plan -var project_id=${{ secrets.PROJECT_ID }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        working-directory: Terraform

      - name: Terraform Apply
        run: terraform apply --auto-approve -var project_id=${{ secrets.PROJECT_ID }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        working-directory: Terraform

      - name: List files in the Terraform directory
        run: |
          pwd
          ls -la Terraform
          cat Terraform/custom.ini 

      - name: Run Ansible Playbooks
        run: |
          ansible-playbook -i Terraform/custom.ini dependencies.yml
          ansible-playbook -i Terraform/custom.ini master.yml
          ansible-playbook -i Terraform/custom.ini nodes.yml
        working-directory: Ansible

      - name: Terraform Destroy
        run: terraform destroy --auto-approve -var project_id=${{ secrets.PROJECT_ID }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        working-directory: Terraform
